/* ============================================================
   RESTAURANT DATA  —  SmartDine Platform
   ============================================================ */

const RESTAURANTS = [
  {
    id:'cloud-pavilion', name:'Cloud Pavilion', nameZh:'云轩',
    tagline:'Fine Cantonese Cuisine',
    cuisine:'Cantonese · Fine Dining',
    categories:['chinese','seafood'],
    priceLevel:4, avgPrice:350, rating:4.9, reviewCount:2847,
    address:'World Trade Centre, 7 Xinhe Street, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'0.8km',
    hours:'11:00 – 22:00', openTime:'11:00', closeTime:'22:00', isReal:true,
    phone:'0577-8888-9999',
    tags:['Fine Dining','Private Room','Seafood','Cantonese'],
    coverGradient:'linear-gradient(140deg,#1a0800,#4a1e00,#1a0800)',
    coverEmoji:'🏮', accentColor:'#c9a84c',
    description:'Rooted in tradition, driven by innovation. Sourcing only the finest seasonal ingredients, Cloud Pavilion creates a dining experience that lingers long after the last bite.',
    features:['🏮 Private Rooms','🚗 Valet Parking','🍷 Wine Cellar','🎂 Birthday Service'],
    menuCategories:['Signature','Seafood','Dim Sum','Meat','Dessert'],
    menu:[
      {id:1,name:'Crispy Boston Lobster',nameZh:'黄金波士顿龙虾',price:368,emoji:'🦞',category:'Signature',desc:'Boston lobster marinated for 12 hours — golden-crisp outside, silky and sweet within.',rating:4.9,orders:1284,isPopular:true},
      {id:2,name:'Buddha Jumps Over the Wall',nameZh:'佛跳墙',price:288,emoji:'🫕',category:'Signature',desc:'18 premium ingredients slow-simmered for 48 hours into a sublime, collagen-rich broth.',rating:4.8,orders:876,isPopular:true},
      {id:3,name:'Osmanthus Honey Roast Duck',nameZh:'桂花蜜汁烤鸭',price:198,emoji:'🦆',category:'Signature',desc:'Century-old Beijing hanging-oven technique with house-made osmanthus honey glaze.',rating:4.9,orders:2103,isPopular:true},
      {id:4,name:'Crystal Prawn Dumplings',nameZh:'晶莹虾饺皇',price:68,emoji:'🥟',category:'Dim Sum',desc:'Wild river prawns wrapped in paper-thin crystal skin — Cantonese dim sum at its finest.',rating:4.7,orders:3421,isPopular:false},
      {id:5,name:'Steamed Songjiang Perch',nameZh:'清蒸鲈鱼',price:168,emoji:'🐟',category:'Seafood',desc:'Live perch steamed to order with aged soy, fresh ginger and sizzling oil.',rating:4.8,orders:654,isPopular:false},
      {id:6,name:'Osmanthus Glutinous Rice Lotus',nameZh:'桂花糯米藕',price:58,emoji:'🍮',category:'Dessert',desc:'Fresh lotus root stuffed with glutinous rice, simmered in osmanthus honey until meltingly soft.',rating:4.7,orders:1876,isPopular:false},
      {id:7,name:'Braised Wagyu Short Rib',nameZh:'红烧和牛肋骨',price:328,emoji:'🥩',category:'Meat',desc:'Wagyu slow-braised for 6 hours in classic Shanghainese red-braising sauce.',rating:4.8,orders:432,isPopular:false},
      {id:8,name:'Wok-Fried King Prawn',nameZh:'干炒明虾',price:148,emoji:'🍤',category:'Seafood',desc:'Jumbo king prawns wok-tossed with XO sauce and crispy garlic.',rating:4.6,orders:987,isPopular:false},
      {id:9,name:'Double-Boiled Snow Pear Soup',nameZh:'雪梨炖雪耳',price:48,emoji:'🍐',category:'Dessert',desc:'Snow pear and silver ear mushroom double-boiled — a classic Cantonese tonic dessert.',rating:4.7,orders:654,isPopular:false},
      {id:10,name:'Peking Duck — Half Bird',nameZh:'北京烤鸭（半只）',price:148,emoji:'🦆',category:'Signature',desc:'Lacquered duck carved tableside, served with thin pancakes, cucumber, scallion and plum sauce.',rating:4.9,orders:876,isPopular:true},
      {id:11,name:'Scallop with Black Truffle',nameZh:'松露带子',price:188,emoji:'🐚',category:'Seafood',desc:'French scallops pan-seared golden, finished with black truffle shavings and cream.',rating:4.8,orders:321,isPopular:false},
      {id:12,name:'Handmade Dimsum Platter',nameZh:'手工点心拼盘',price:88,emoji:'🧆',category:'Dim Sum',desc:'Six handcrafted dim sum daily: har gow, siu mai, rice noodle roll, egg tart, BBQ pork bun, sticky rice.',rating:4.8,orders:1234,isPopular:false},
    ],
  },
  {
    id:'tokyo-shokunin', name:'Tokyo Shokunin', nameZh:'东京匠心',
    tagline:'Authentic Japanese Cuisine',
    cuisine:'Japanese · Sushi · Ramen',
    categories:['japanese'],
    priceLevel:3, avgPrice:188, rating:4.7, reviewCount:1923,
    address:'Wanxiang City Mall B1, Minsheng Road, Ouhai District, Wenzhou',
    district:'Ouhai District', distance:'1.2km',
    hours:'11:30 – 22:30', openTime:'11:30', closeTime:'22:30', isReal:true,
    phone:'0577-8628-0099',
    tags:['Sushi','Ramen','Omakase','Sake'],
    coverGradient:'linear-gradient(140deg,#050515,#0f0a30,#050515)',
    coverEmoji:'🍱', accentColor:'#7c9fe8',
    description:'Our chef trained in Tokyo for 15 years. Ingredients are flown in daily from Tsukiji. From exquisite omakase to authentic Hakata ramen.',
    features:['🎋 Omakase Menu','🍶 Premium Sake','🎌 Tatami Rooms','🐟 Daily Air Import'],
    menuCategories:['Sashimi','Sushi','Ramen','Tempura','Dessert'],
    menu:[
      {id:1,name:'Otoro Sashimi',nameZh:'大肥金枪鱼刺身',price:298,emoji:'🐟',category:'Sashimi',desc:'Bluefin tuna fatty tuna, flown in daily from Tsukiji — oil-rich and melts on the tongue.',rating:4.9,orders:432,isPopular:true},
      {id:2,name:'Wagyu Sushi Platter',nameZh:'和牛寿司拼盘',price:388,emoji:'🍣',category:'Sushi',desc:'8-piece premium wagyu and seasonal seafood sushi, prepared by the master chef.',rating:4.8,orders:876,isPopular:true},
      {id:3,name:'Tonkotsu Ramen',nameZh:'博多豚骨拉面',price:88,emoji:'🍜',category:'Ramen',desc:'Rich pork bone broth simmered 18 hours, with chashu and soft-boiled egg.',rating:4.7,orders:2341,isPopular:true},
      {id:4,name:'Crispy Gyoza (8pc)',nameZh:'煎饺',price:58,emoji:'🥟',category:'Ramen',desc:'Hand-folded pork and cabbage dumplings, pan-fried to a golden crisp.',rating:4.6,orders:1987,isPopular:false},
      {id:5,name:'Ebi Tempura Set',nameZh:'天妇罗拼盘',price:128,emoji:'🍤',category:'Tempura',desc:'Tiger prawn and seasonal vegetable tempura with dashi dipping sauce.',rating:4.7,orders:654,isPopular:false},
      {id:6,name:'Matcha Kakigori',nameZh:'抹茶刨冰',price:48,emoji:'🍵',category:'Dessert',desc:'Fine shaved ice with Uji matcha syrup, red bean and mochi. Refreshingly elegant.',rating:4.5,orders:876,isPopular:false},
      {id:7,name:'Miso Black Cod',nameZh:'西京烧银鳕鱼',price:228,emoji:'🐠',category:'Sashimi',desc:'Black cod marinated 48 hours in Saikyo miso, grilled until golden — butter-smooth flesh.',rating:4.9,orders:543,isPopular:true},
      {id:8,name:'Karaage Chicken',nameZh:'唐扬炸鸡',price:68,emoji:'🍗',category:'Tempura',desc:'Marinated chicken thigh in secret batter, fried to crunchy perfection with lemon and mayo.',rating:4.6,orders:2345,isPopular:false},
      {id:9,name:'Wagyu Beef Udon',nameZh:'和牛乌冬面',price:128,emoji:'🍜',category:'Ramen',desc:'Rich kombu dashi broth with sliced wagyu over silky thick udon. Deeply comforting.',rating:4.7,orders:1234,isPopular:false},
    ],
  },
  {
    id:'bella-roma', name:'Bella Roma', nameZh:'贝拉罗马',
    tagline:'Authentic Italian Dining',
    cuisine:'Italian · Pizza · Pasta',
    categories:['western'],
    priceLevel:3, avgPrice:198, rating:4.6, reviewCount:1456,
    address:'Lidu City Mall 2F, Binhai Avenue, Longwan District, Wenzhou',
    district:'Longwan District', distance:'2.1km',
    hours:'12:00 – 23:00', openTime:'12:00', closeTime:'23:00', isReal:true,
    phone:'0577-8882-7788',
    tags:['Pizza','Pasta','Romantic','Italian Wine'],
    coverGradient:'linear-gradient(140deg,#1a0a08,#3d1810,#1a0a08)',
    coverEmoji:'🍕', accentColor:'#e8724c',
    description:'A wood-fired oven and imported Italian ingredients bring the soul of Rome to Wenzhou. Every handmade pasta is a tribute to Italian culinary heritage.',
    features:['🍕 Wood-fired Oven','🍝 Handmade Pasta','🍷 Italian Wine','💑 Romantic Setting'],
    menuCategories:['Starter','Pizza','Pasta','Main','Dessert'],
    menu:[
      {id:1,name:'Truffle Margherita Pizza',nameZh:'松露玛格丽特披萨',price:158,emoji:'🍕',category:'Pizza',desc:'San Marzano tomatoes, buffalo mozzarella, fresh basil, black truffle on wood-fired crust.',rating:4.8,orders:2103,isPopular:true},
      {id:2,name:'Carbonara Classica',nameZh:'经典卡邦尼意面',price:128,emoji:'🍝',category:'Pasta',desc:'Guanciale, Pecorino Romano, egg yolk and black pepper. No cream — the real Roman deal.',rating:4.7,orders:1876,isPopular:true},
      {id:3,name:'Osso Buco Milanese',nameZh:'米兰式烩小牛膝',price:268,emoji:'🥩',category:'Main',desc:'Slow-braised veal shank with gremolata and saffron risotto.',rating:4.8,orders:345,isPopular:false},
      {id:4,name:'Tiramisu',nameZh:'提拉米苏',price:68,emoji:'☕',category:'Dessert',desc:'Mascarpone, espresso-soaked ladyfingers, dusted with cocoa. The classic done right.',rating:4.9,orders:3241,isPopular:true},
      {id:5,name:'Burrata Caprese',nameZh:'布拉塔卡布里沙拉',price:98,emoji:'🥗',category:'Starter',desc:'Creamy burrata, heirloom tomatoes, aged balsamic and fresh basil oil.',rating:4.6,orders:876,isPopular:false},
      {id:6,name:'Seafood Linguine',nameZh:'海鲜扁面',price:178,emoji:'🦐',category:'Pasta',desc:'Clams, mussels, squid and cherry tomatoes in white wine sauce.',rating:4.7,orders:654,isPopular:false},
      {id:7,name:'Cacio e Pepe',nameZh:'奶酪黑胡椒意面',price:118,emoji:'🍝',category:'Pasta',desc:"Rome's ancient pasta — Pecorino Romano, black pepper, and nothing else. Profound simplicity.",rating:4.8,orders:876,isPopular:false},
      {id:8,name:'Panna Cotta',nameZh:'意式奶冻',price:58,emoji:'🍮',category:'Dessert',desc:'Silky vanilla cream panna cotta with fresh strawberry coulis. Light and elegant.',rating:4.7,orders:1234,isPopular:false},
      {id:9,name:'Prosciutto & Melon',nameZh:'帕尔玛火腿配香瓜',price:98,emoji:'🍈',category:'Starter',desc:'18-month aged Parma ham with sweet cantaloupe — the perfect sweet-salty Italian starter.',rating:4.6,orders:543,isPopular:false},
    ],
  },
  {
    id:'sichuan-dao', name:'Chuan La Dao', nameZh:'川辣道',
    tagline:'Authentic Sichuan Flavours',
    cuisine:'Sichuan · Spicy',
    categories:['chinese'],
    priceLevel:2, avgPrice:88, rating:4.8, reviewCount:4231,
    address:'Xintiandi Plaza 3F, Wuma Street, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'1.5km',
    hours:'10:30 – 23:30', openTime:'10:30', closeTime:'23:30', isReal:true,
    phone:'0577-8850-9988',
    tags:['Sichuan','Spicy','Authentic','Popular'],
    coverGradient:'linear-gradient(140deg,#1a0500,#4a0a00,#1a0500)',
    coverEmoji:'🌶️', accentColor:'#e84c4c',
    description:'Authentic Sichuan recipes passed down from a century-old Chengdu establishment. Hanyuan Sichuan pepper and Pixian chilli paste — no compromise, no shortcuts.',
    features:['🌶️ Adjustable Spice','🫙 House Chilli Paste','🧄 Fresh Daily','🛵 Delivery Available'],
    menuCategories:['Sichuan Classics','Snacks','Vegetables','Staples'],
    menu:[
      {id:1,name:'Mapo Tofu',nameZh:'麻婆豆腐',price:48,emoji:'🫘',category:'Sichuan Classics',desc:'Chen Mapo recipe — Hanyuan Sichuan pepper, Pixian doubanjiang. Numbing, spicy, addictive.',rating:4.9,orders:5632,isPopular:true},
      {id:2,name:'Kung Pao Chicken',nameZh:'宫保鸡丁',price:68,emoji:'🍗',category:'Sichuan Classics',desc:'Tender chicken with peanuts, sweet-sour and gently spicy. Perfect over rice.',rating:4.8,orders:4321,isPopular:true},
      {id:3,name:'Mao Xuewang',nameZh:'毛血旺',price:88,emoji:'🥘',category:'Sichuan Classics',desc:'Duck blood, tripe, yellow throat and beansprouts in a fiery red broth. Bring tissues.',rating:4.9,orders:3876,isPopular:true},
      {id:4,name:'Dan Dan Noodles',nameZh:'担担面',price:28,emoji:'🍜',category:'Snacks',desc:'Thin noodles with preserved vegetables, minced pork and peanuts. Spicy but not harsh.',rating:4.7,orders:6543,isPopular:false},
      {id:5,name:'Twice-Cooked Pork',nameZh:'回锅肉',price:68,emoji:'🥩',category:'Sichuan Classics',desc:'Pork belly with garlic shoots and Pixian doubanjiang — the quintessential Sichuan staple.',rating:4.6,orders:2341,isPopular:false},
      {id:6,name:'Red Oil Wontons',nameZh:'红油抄手',price:32,emoji:'🥟',category:'Snacks',desc:'Thin-skinned pork wontons in house-made chilli oil. Spicy, fragrant, irresistible.',rating:4.8,orders:4567,isPopular:false},
      {id:7,name:'Dry-Pot Cauliflower',nameZh:'干锅有机花椰菜',price:52,emoji:'🥦',category:'Vegetables',desc:'Organic cauliflower stir-fried with pork belly and chilli until edges are slightly charred.',rating:4.7,orders:3456,isPopular:false},
      {id:8,name:'Shui Zhu Fish Fillet',nameZh:'水煮鱼片',price:88,emoji:'🐟',category:'Sichuan Classics',desc:'Silky grass carp fillets floating in numbing-spicy red broth, finished with a hot Sichuan pepper oil pour.',rating:4.9,orders:5678,isPopular:true},
      {id:9,name:'Steamed Rice',nameZh:'白米饭',price:6,emoji:'🍚',category:'Staples',desc:'Perfectly steamed fragrant jasmine rice. The essential companion to every Sichuan dish.',rating:4.5,orders:9876,isPopular:false},
    ],
  },
  {
    id:'prime-house', name:'The Prime House', nameZh:'极品牛排馆',
    tagline:'Premium Cuts & Fine Wines',
    cuisine:'Steakhouse · Western',
    categories:['western'],
    priceLevel:4, avgPrice:488, rating:4.5, reviewCount:876,
    address:'Century Lotus Hotel 30F, Jiangbin Road, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'3.2km',
    hours:'17:00 – 23:00', openTime:'17:00', closeTime:'23:00', isReal:true,
    phone:'0577-8988-6688',
    tags:['Steak','Wagyu','Fine Dining','City View'],
    coverGradient:'linear-gradient(140deg,#0a0808,#1f1008,#0a0808)',
    coverEmoji:'🥩', accentColor:'#d4a574',
    description:"The world's finest cuts paired with sweeping city views over Wenzhou. A dry-ageing room holds prime selections from Japan, Australia and the USA, alongside 400+ wines.",
    features:['🥩 Dry-Aged Beef','🍷 400+ Wines','🌃 City View','🎩 Dress Code'],
    menuCategories:['Starter','Steak','Seafood','Dessert'],
    menu:[
      {id:1,name:'A5 Wagyu Ribeye (200g)',nameZh:'A5和牛肋眼',price:888,emoji:'🥩',category:'Steak',desc:'Japanese A5 Wagyu, marble score 12, served with truffle butter and roasted bone marrow.',rating:4.9,orders:234,isPopular:true},
      {id:2,name:'USDA Prime Tomahawk (1kg)',nameZh:'USDA战斧牛排',price:688,emoji:'🍖',category:'Steak',desc:'28-day dry-aged USDA Prime tomahawk, carved tableside with chimichurri and smoked salt.',rating:4.8,orders:156,isPopular:true},
      {id:3,name:'Lobster Thermidor',nameZh:'黄油焗龙虾',price:488,emoji:'🦞',category:'Seafood',desc:'Whole Maine lobster with classic thermidor sauce, gratinated to golden perfection.',rating:4.7,orders:198,isPopular:false},
      {id:4,name:'Caesar Salad (tableside)',nameZh:'桌边凯撒沙拉',price:128,emoji:'🥗',category:'Starter',desc:'Prepared tableside with house-made anchovy dressing, parmesan and sourdough croutons.',rating:4.6,orders:543,isPopular:false},
      {id:5,name:'Crème Brûlée',nameZh:'法式焦糖布丁',price:88,emoji:'🍮',category:'Dessert',desc:'Classic vanilla bean custard with caramelised sugar crust and seasonal berries.',rating:4.8,orders:432,isPopular:false},
      {id:6,name:'Foie Gras Parfait',nameZh:'法国鹅肝派',price:228,emoji:'🫙',category:'Starter',desc:'Silky foie gras parfait with Sauternes jelly, brioche toast and pickled grapes.',rating:4.7,orders:287,isPopular:false},
    ],
  },
  {
    id:'hong-tu-seafood', name:'Hong Tu Seafood', nameZh:'鸿图海鲜楼',
    tagline:'Fresh Catch, Cantonese Style',
    cuisine:'Seafood · Cantonese',
    categories:['seafood','chinese'],
    priceLevel:3, avgPrice:228, rating:4.8, reviewCount:3124,
    address:'Huanqiu Center 4F, Jingshan Road, Ouhai District, Wenzhou',
    district:'Ouhai District', distance:'4.5km',
    hours:'10:00 – 22:00', openTime:'10:00', closeTime:'22:00', isReal:true,
    phone:'0577-8582-3399',
    tags:['Seafood','Live Tank','Cantonese','Family Dining'],
    coverGradient:'linear-gradient(140deg,#001515,#003030,#001515)',
    coverEmoji:'🦀', accentColor:'#4ce8c8',
    description:'Live seafood sourced daily from the East China Sea. Cantonese chefs cook to order — fresh, sweet, nothing lost in translation.',
    features:['🐟 Live Seafood Tanks','🔪 Cantonese Chefs','👨‍👩‍👧‍👦 Family Dining','🚢 Daily Fresh Catch'],
    menuCategories:['Crab','Prawn','Shell','Fish','Premium'],
    menu:[
      {id:1,name:'Steamed Snow Crab',nameZh:'清蒸雪蟹',price:268,emoji:'🦀',category:'Crab',desc:'Snow crab steamed live and served with aged vinegar and ginger. Meat bouncy and sweet.',rating:4.9,orders:876,isPopular:true},
      {id:2,name:'Garlic Steamed Scallops',nameZh:'蒜蓉粉丝蒸扇贝',price:128,emoji:'🐚',category:'Shell',desc:'Fresh scallops on glass noodles with garlic and spring onion, steamed to fragrant perfection.',rating:4.8,orders:2341,isPopular:true},
      {id:3,name:'Salt & Pepper Mantis Shrimp',nameZh:'椒盐皮皮虾',price:98,emoji:'🦐',category:'Prawn',desc:'Live mantis shrimp fried crispy, seasoned with salt, pepper and garlic. Shell-crackingly good.',rating:4.7,orders:3456,isPopular:true},
      {id:4,name:'Braised Sea Cucumber',nameZh:'红烧辽参',price:298,emoji:'🫘',category:'Premium',desc:'Liaoning sea cucumber red-braised in rich sauce. Collagen-rich, silky, deeply nourishing.',rating:4.8,orders:234,isPopular:false},
      {id:5,name:'Fish Head Casserole',nameZh:'砂锅鱼头',price:168,emoji:'🐟',category:'Fish',desc:'Large fish head simmered in clay pot with tofu. Rich, silky broth — deeply comforting.',rating:4.6,orders:987,isPopular:false},
      {id:6,name:'XO Sauce Clams',nameZh:'XO酱炒花蛤',price:68,emoji:'🐌',category:'Shell',desc:'Live clams wok-tossed with house XO sauce. Intensely savoury, great with beer.',rating:4.7,orders:4321,isPopular:false},
    ],
  },
  {
    id:'lao-zhang-hotpot', name:'Lao Zhang Hot Pot', nameZh:'老张涮肉',
    tagline:'Old Beijing Copper Pot',
    cuisine:'Hot Pot · Beijing',
    categories:['hotpot','chinese'],
    priceLevel:2, avgPrice:118, rating:4.7, reviewCount:5678,
    address:'Jintong Times Square 3F, Shanhe Street, Longwan District, Wenzhou',
    district:'Longwan District', distance:'5.8km',
    hours:'11:00 – 23:00', openTime:'11:00', closeTime:'23:00', isReal:true,
    phone:'0577-8550-8877',
    tags:['Hot Pot','Beijing','Copper Pot','Lamb'],
    coverGradient:'linear-gradient(140deg,#1a0800,#2d1200,#1a0800)',
    coverEmoji:'🫕', accentColor:'#e8a44c',
    description:'Authentic Beijing copper-pot shabu-shabu, with hand-cut Inner Mongolian lamb and a century-old broth. Sesame sauce mixed fresh to order.',
    features:['🐑 Hand-cut Mongolian Lamb','🔥 Charcoal Copper Pot','🥣 Fresh Sesame Sauce','❄️ Slice to Order'],
    menuCategories:['Meat','Vegetable','Sauce','Staple'],
    menu:[
      {id:1,name:'Hand-cut Lamb Roll',nameZh:'手切内蒙羊肉卷',price:88,emoji:'🐑',category:'Meat',desc:'Inner Mongolian grass-fed lamb, hand-sliced thin. In the pot for 3 seconds — tender and gamble-free.',rating:4.9,orders:8765,isPopular:true},
      {id:2,name:'Premium Beef Slices',nameZh:'精选肥牛片',price:68,emoji:'🥩',category:'Meat',desc:'Australian grain-fed wagyu-style beef. Beautiful marbling, cooks in seconds.',rating:4.7,orders:6543,isPopular:true},
      {id:3,name:'Sesame Sauce Set',nameZh:'麻酱调料套餐',price:18,emoji:'🥣',category:'Sauce',desc:'House-ground sesame paste with fermented tofu, garlic chives and spring onion.',rating:4.8,orders:9876,isPopular:false},
      {id:4,name:'Mushroom Platter',nameZh:'菌菇拼盘',price:48,emoji:'🍄',category:'Vegetable',desc:'Enoki, oyster, shiitake and tea tree mushrooms. Springy and broth-absorbent.',rating:4.6,orders:4321,isPopular:false},
      {id:5,name:'Handmade Tofu',nameZh:'手工嫩豆腐',price:28,emoji:'🫘',category:'Vegetable',desc:'Freshly made daily, silky inside and smooth outside after cooking.',rating:4.5,orders:3456,isPopular:false},
      {id:6,name:'Hand-rolled Noodles',nameZh:'手擀面条',price:22,emoji:'🍜',category:'Staple',desc:'Hand-rolled thick noodles — chewy, broth-absorbing, the perfect ending.',rating:4.7,orders:5432,isPopular:false},
    ],
  },
  {
    id:'seoul-garden', name:'Seoul Garden', nameZh:'首尔花园',
    tagline:'Premium Korean BBQ',
    cuisine:'Korean BBQ',
    categories:['korean'],
    priceLevel:3, avgPrice:168, rating:4.6, reviewCount:2345,
    address:'Wanda Plaza 5F, Shuangyu Road, Longwan District, Wenzhou',
    district:'Longwan District', distance:'3.8km',
    hours:'11:00 – 23:00', openTime:'11:00', closeTime:'23:00', isReal:true,
    phone:'0577-8879-6688',
    tags:['Korean BBQ','KBBQ','Unlimited Banchan','Group Dining'],
    coverGradient:'linear-gradient(140deg,#100a1a,#1a0a2d,#100a1a)',
    coverEmoji:'🥓', accentColor:'#b87cf0',
    description:'Premium Iberian pork belly and USDA marinated short ribs with unlimited Korean side dishes. Smart ventilation at every table for a smoke-free experience.',
    features:['🥓 Premium Meats','♾️ Unlimited Banchan','💨 Smart Ventilation','🎵 K-pop Ambiance'],
    menuCategories:['BBQ','Stew','Staple','Snack'],
    menu:[
      {id:1,name:'Thick-cut Pork Belly',nameZh:'厚切五花肉',price:98,emoji:'🥓',category:'BBQ',desc:'Iberian pork belly, thick-cut and rich with fat. Grill until golden, wrap in lettuce.',rating:4.8,orders:4321,isPopular:true},
      {id:2,name:'Galbi (Marinated Short Rib)',nameZh:'腌制牛排骨',price:178,emoji:'🍖',category:'BBQ',desc:'Beef short rib marinated in pear juice for 24 hours. Caramelises beautifully on the grill.',rating:4.9,orders:2876,isPopular:true},
      {id:3,name:'Dolsot Bibimbap',nameZh:'石锅拌饭',price:68,emoji:'🍚',category:'Staple',desc:'Crispy-bottomed stone pot rice with seasonal vegetables and beef, topped with egg.',rating:4.7,orders:3456,isPopular:true},
      {id:4,name:'Budae Jjigae (Army Stew)',nameZh:'部队锅',price:88,emoji:'🍲',category:'Stew',desc:'Ham, ramen, tofu and kimchi in a spicy broth. Korea\'s beloved comfort classic.',rating:4.6,orders:2341,isPopular:false},
      {id:5,name:'Haemul Pajeon',nameZh:'海鲜葱饼',price:58,emoji:'🥞',category:'Snack',desc:'Crispy seafood and spring onion pancake. Dip in soy-vinegar sauce.',rating:4.5,orders:1876,isPopular:false},
      {id:6,name:'Sundubu Jjigae',nameZh:'嫩豆腐汤',price:48,emoji:'🫕',category:'Stew',desc:'Soft tofu with clams and seafood in a bright spicy broth. Warming and soothing.',rating:4.6,orders:2109,isPopular:false},
    ],
  },
  {
    id:'chongqing-hotpot', name:'Chongqing Hot Pot King', nameZh:'重庆火锅王',
    tagline:'Authentic Chongqing Tallow Broth',
    cuisine:'Chongqing Hot Pot',
    categories:['hotpot','chinese'],
    priceLevel:2, avgPrice:108, rating:4.8, reviewCount:6321,
    address:'Vanke Mall B2, Mingjing Road, Ouhai District, Wenzhou',
    district:'Ouhai District', distance:'2.3km',
    hours:'10:00 – 23:00', openTime:'10:00', closeTime:'23:00', isReal:true,
    phone:'0577-8888-5566',
    tags:['Tallow Broth','Yin-Yang Pot','Tripe','Duck Intestine'],
    coverGradient:'linear-gradient(140deg,#1f0000,#4a0000,#1f0000)',
    coverEmoji:'🌶️', accentColor:'#ff4444',
    description:'A 30-year tallow broth recipe from old Chongqing. Hanyuan Sichuan pepper and Pixian doubanjiang. Fresh tripe in 7 seconds — this is the real deal.',
    features:['🌶️ Tallow Broth','🫕 Yin-Yang Option','🐄 Fresh Sliced Meat','🕑 Open Until 11pm'],
    menuCategories:['Meat','Vegetable','Staple','Drink'],
    menu:[
      {id:1,name:'Fresh Tripe (Maodu)',nameZh:'新鲜毛肚',price:58,emoji:'🫘',category:'Meat',desc:'Freshly sourced tripe: 7 seconds in the broth. Crunchy, tender — the Chongqing must-order.',rating:4.9,orders:9876,isPopular:true},
      {id:2,name:'Duck Intestine',nameZh:'脆嫩鸭肠',price:48,emoji:'🦆',category:'Meat',desc:'Duck intestine, barely 8 seconds in the pot. Snappy texture, soaks up all the spicy broth.',rating:4.8,orders:7654,isPopular:true},
      {id:3,name:'Wagyu Beef Slices',nameZh:'和牛肥牛卷',price:88,emoji:'🥩',category:'Meat',desc:'Australian wagyu sliced thin — melts in the fiery broth, tender and rich.',rating:4.7,orders:5432,isPopular:true},
      {id:4,name:'Lotus Root',nameZh:'脆藕片',price:22,emoji:'🌿',category:'Vegetable',desc:'Sliced lotus root: floury and broth-absorbing after cooking. A cool contrast to the spice.',rating:4.6,orders:4321,isPopular:false},
      {id:5,name:'Handmade Rice Cake',nameZh:'手工年糕',price:18,emoji:'🍡',category:'Staple',desc:'Glutinous rice cake, soft and chewy after cooking — soaks up all the rich tallow broth.',rating:4.5,orders:3210,isPopular:false},
    ],
  },
  {
    id:'din-tai-fung', name:'Din Tai Fung', nameZh:'鼎泰丰',
    tagline:'World-Class Dim Sum',
    cuisine:'Taiwanese · Dim Sum',
    categories:['chinese'],
    priceLevel:3, avgPrice:128, rating:4.8, reviewCount:4567,
    address:'Henglong Plaza 3F, Renmin Road, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'1.8km',
    hours:'11:00 – 21:30', openTime:'11:00', closeTime:'21:30', isReal:true,
    phone:'0577-8688-1688',
    tags:['XLB','Dim Sum','Michelin','Queue-worthy'],
    coverGradient:'linear-gradient(140deg,#0a0a1a,#14102a,#0a0a1a)',
    coverEmoji:'🥟', accentColor:'#9a7cf0',
    description:'Michelin-recommended. 18 perfect folds on every xiaolongbao. Each one holds a small ocean of broth inside. Taiwanese dim sum culture at its most refined.',
    features:['⭐ Michelin Recommended','🥟 18-Fold XLB','🫕 Made Fresh Daily','🍜 Handmade Noodles'],
    menuCategories:['Xiaolongbao','Dim Sum','Noodle','Dessert'],
    menu:[
      {id:1,name:'Xiao Long Bao (10pc)',nameZh:'招牌小笼包',price:68,emoji:'🥟',category:'Xiaolongbao',desc:'18 perfect folds, thin skin, a flood of broth inside. The gold standard in dumpling craftsmanship.',rating:4.9,orders:12345,isPopular:true},
      {id:2,name:'Truffle XLB (6pc)',nameZh:'松露小笼包',price:108,emoji:'🫕',category:'Xiaolongbao',desc:'Classic XLB elevated with black truffle. Luxurious fragrance in every bite.',rating:4.8,orders:4321,isPopular:true},
      {id:3,name:'Shrimp Fried Rice',nameZh:'虾仁蛋炒饭',price:78,emoji:'🍚',category:'Noodle',desc:'Grain-by-grain fried rice with fresh prawns. Perfect wok hei — smoky and light.',rating:4.7,orders:5678,isPopular:true},
      {id:4,name:'Red Oil Wontons',nameZh:'红油馄饨',price:48,emoji:'🌶️',category:'Dim Sum',desc:'Thin-skinned wontons in house-made chilli oil. Spicy, savoury, deeply addictive.',rating:4.6,orders:3456,isPopular:false},
      {id:5,name:'Mango Rice Cake',nameZh:'芒果米糕',price:38,emoji:'🥭',category:'Dessert',desc:'Soft glutinous rice cake with fresh mango. Sweetly refreshing, the perfect end.',rating:4.7,orders:2345,isPopular:false},
    ],
  },
  {
    id:'le-bistro', name:'Le Petit Bistro', nameZh:'Le Bistro',
    tagline:'French Cuisine & Wine',
    cuisine:'French · Western',
    categories:['western'],
    priceLevel:3, avgPrice:238, rating:4.5, reviewCount:987,
    address:'88 Gongxue Road, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'3.1km',
    hours:'11:30 – 22:00', openTime:'11:30', closeTime:'22:00', isReal:true,
    phone:'0577-8803-8899',
    tags:['French','Wine','Date Night','Classic'],
    coverGradient:'linear-gradient(140deg,#08080f,#141018,#08080f)',
    coverEmoji:'🍷', accentColor:'#c46b8a',
    description:"A quiet French bistro tucked into Lucheng. Lyon-trained chef, Provence-sourced ingredients, 100 handpicked wines. Perfect for intimate occasions.",
    features:['🍷 100+ Wine Labels','🥐 French Brunch','🌹 Romantic Setting','🌳 Garden Terrace'],
    menuCategories:['Starter','Main','Dessert'],
    menu:[
      {id:1,name:'Foie Gras Terrine',nameZh:'法式鹅肝冻',price:188,emoji:'🫙',category:'Starter',desc:'Duck foie gras terrine with fig jam and brioche toast. Melts instantly — impossibly rich.',rating:4.8,orders:567,isPopular:true},
      {id:2,name:'Duck Confit',nameZh:'油封鸭腿',price:218,emoji:'🦆',category:'Main',desc:'Duck leg slow-cooked 8 hours in its own fat. Skin crunchy, flesh falls from the bone.',rating:4.7,orders:432,isPopular:true},
      {id:3,name:'Bouillabaisse',nameZh:'马赛鱼汤',price:198,emoji:'🫕',category:'Main',desc:"Marseille-style seafood stew with saffron, fennel and rouille croutons. Deeply complex.",rating:4.6,orders:321,isPopular:false},
      {id:4,name:'Crêpe Suzette (tableside)',nameZh:'橙汁可丽饼',price:88,emoji:'🥞',category:'Dessert',desc:'Tableside flambé performance with orange caramel sauce. Dramatic and delicious.',rating:4.9,orders:765,isPopular:true},
    ],
  },
  {
    id:'spice-india', name:'Spice India', nameZh:'香料印度',
    tagline:'North Indian Curries & Tandoor',
    cuisine:'Indian · Asian',
    categories:['asian'],
    priceLevel:2, avgPrice:98, rating:4.6, reviewCount:1234,
    address:'22 Chezhan Avenue, Ouhai District, Wenzhou',
    district:'Ouhai District', distance:'2.6km',
    hours:'11:00 – 22:00', openTime:'11:00', closeTime:'22:00', isReal:true,
    phone:'0577-8848-3377',
    tags:['Curry','Tandoor','Naan','Vegetarian-Friendly'],
    coverGradient:'linear-gradient(140deg,#1a0f00,#3a1a00,#1a0f00)',
    coverEmoji:'🍛', accentColor:'#e8a030',
    description:'Mumbai-trained chef with freshly ground spices. Authentic North Indian curries, tandoor-fired naans and rich gravies that have no shortcut.',
    features:['🫙 House-ground Spices','🍞 Tandoor Naan','🌿 Veg Options','🎵 Indian Ambiance'],
    menuCategories:['Curry','Grill','Bread','Dessert'],
    menu:[
      {id:1,name:'Butter Chicken Curry',nameZh:'黄油鸡咖喱',price:88,emoji:'🍛',category:'Curry',desc:'Tender chicken in rich tomato-butter curry. Mildly spiced, velvety and crowd-pleasing.',rating:4.8,orders:3456,isPopular:true},
      {id:2,name:'Lamb Rogan Josh',nameZh:'克什米尔羊肉咖喱',price:108,emoji:'🥘',category:'Curry',desc:'Slow-cooked lamb in Kashmiri dried chillies and warming spices. Bold and layered.',rating:4.7,orders:2109,isPopular:true},
      {id:3,name:'Garlic Naan (3pc)',nameZh:'蒜蓉烤馕',price:28,emoji:'🍞',category:'Bread',desc:'Tandoor-fired naan brushed with garlic butter. Blistered, soft and utterly perfect for dipping.',rating:4.9,orders:5678,isPopular:true},
      {id:4,name:'Palak Paneer',nameZh:'菠菜奶酪',price:68,emoji:'🌿',category:'Curry',desc:'Fresh paneer in bright herby spinach sauce. The best vegetarian choice on the menu.',rating:4.5,orders:1234,isPopular:false},
      {id:5,name:'Mango Lassi',nameZh:'芒果酸奶昔',price:28,emoji:'🥭',category:'Dessert',desc:'Fresh mango blended with creamy yoghurt and a pinch of cardamom. The ultimate curry cooler.',rating:4.7,orders:3210,isPopular:false},
    ],
  },
  {
    id:'vietnam-pho', name:'Hanoi Kitchen', nameZh:'河内越饭',
    tagline:'Vietnamese Street Food',
    cuisine:'Vietnamese · Asian',
    categories:['asian'],
    priceLevel:1, avgPrice:68, rating:4.5, reviewCount:2109,
    address:'36 Xinchen Road, Ouhai District, Wenzhou',
    district:'Ouhai District', distance:'3.4km',
    hours:'10:00 – 21:00', openTime:'10:00', closeTime:'21:00', isReal:true,
    phone:'0577-8804-9922',
    tags:['Pho','Spring Rolls','Healthy','Vietnamese Coffee'],
    coverGradient:'linear-gradient(140deg,#001a0a,#003015,#001a0a)',
    coverEmoji:'🍜', accentColor:'#50c878',
    description:"Hanoi street food brought to Wenzhou. Bone broth simmered 12 hours, fresh herbs and rice noodles that are lighter on the stomach but huge on flavour.",
    features:['🍜 12-hour Bone Broth','🌿 Fresh Herbs','☕ Vietnamese Coffee','🥗 Light & Healthy'],
    menuCategories:['Noodles','Spring Rolls','Staple','Drink'],
    menu:[
      {id:1,name:'Pho Bo (Beef Noodle)',nameZh:'越南牛肉河粉',price:48,emoji:'🍜',category:'Noodles',desc:'12-hour bone broth, crystal clear and deeply savoury, with sliced beef and fresh herb plate.',rating:4.8,orders:5432,isPopular:true},
      {id:2,name:'Fresh Prawn Spring Rolls (4pc)',nameZh:'越南鲜虾春卷',price:38,emoji:'🫔',category:'Spring Rolls',desc:'Rice paper rolls with fresh prawns, vermicelli and lettuce. Light, clean, addictive with peanut sauce.',rating:4.7,orders:4321,isPopular:true},
      {id:3,name:'Bun Bo Hue',nameZh:'顺化牛肉米线',price:52,emoji:'🌶️',category:'Noodles',desc:'Hue-style spicy noodle soup — bolder than pho, with pork trotter and lemongrass.',rating:4.6,orders:2345,isPopular:false},
      {id:4,name:'Vietnamese Iced Coffee',nameZh:'越南冰咖啡',price:28,emoji:'☕',category:'Drink',desc:'Drip coffee over condensed milk and ice. Sweet, intense and wonderfully cooling.',rating:4.9,orders:6543,isPopular:true},
    ],
  },
  {
    id:'barbeque-brazil', name:'Fogo Brasil', nameZh:'巴西火焰烤肉',
    tagline:'Brazilian Churrascaria',
    cuisine:'Brazilian · Western',
    categories:['western'],
    priceLevel:3, avgPrice:268, rating:4.7, reviewCount:1876,
    address:'Times Square 6F, Longwan Boulevard, Longwan District, Wenzhou',
    district:'Longwan District', distance:'4.2km',
    hours:'11:30 – 22:30', openTime:'11:30', closeTime:'22:30', isReal:true,
    phone:'0577-8879-8866',
    tags:['Brazilian BBQ','All-you-can-eat','Picanha','Group Dining'],
    coverGradient:'linear-gradient(140deg,#0f0a00,#201400,#0f0a00)',
    coverEmoji:'🍖', accentColor:'#ff8c00',
    description:'Authentic Brazilian churrascaria — gauchos roam the room carving 15+ cuts tableside. Unlimited salad bar included. Meat lovers\' paradise.',
    features:['🍖 15+ Cuts','🥗 Unlimited Salad Bar','🗡️ Tableside Carving','🍻 Imported Drinks'],
    menuCategories:['Beef','Pork','Chicken','Other'],
    menu:[
      {id:1,name:'Picanha (Rump Cap)',nameZh:'皮卡尼亚臀盖肉',price:0,emoji:'🥩',category:'Beef',desc:"Brazil's favourite cut — fat cap and crispy crust over pink, juicy meat. The centrepiece.",rating:4.9,orders:8765,isPopular:true},
      {id:2,name:'Fraldinha (Flank)',nameZh:'腹肉',price:0,emoji:'🍖',category:'Beef',desc:'Bold-flavoured flank steak with a satisfying chew. Outstanding with the house chimichurri.',rating:4.7,orders:6543,isPopular:true},
      {id:3,name:'Costela (Beef Ribs)',nameZh:'牛肋骨',price:0,emoji:'🦴',category:'Beef',desc:'Beef ribs slow-cooked for 4 hours over charcoal. The meat beside the bone is the best part.',rating:4.8,orders:5432,isPopular:true},
      {id:4,name:'Linguiça (Pork Sausage)',nameZh:'巴西香肠',price:0,emoji:'🌭',category:'Pork',desc:'Brazilian spiced pork sausage — snappy casing, juicy inside, herby and smoky.',rating:4.6,orders:4321,isPopular:false},
      {id:5,name:'Chicken Wrapped in Bacon',nameZh:'培根鸡腿卷',price:0,emoji:'🍗',category:'Chicken',desc:'Marinated chicken thigh wrapped in thick-cut bacon, charcoal-roasted until golden.',rating:4.5,orders:3210,isPopular:false},
    ],
  },
  {
    id:'dim-sum-palace', name:'Dim Sum Palace', nameZh:'点心宫',
    tagline:'Cantonese Yum Cha',
    cuisine:'Cantonese · Dim Sum',
    categories:['chinese'],
    priceLevel:2, avgPrice:88, rating:4.7, reviewCount:3456,
    address:'Wumei Square A, Jiefang Street, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'2.9km',
    hours:'07:00 – 15:00', openTime:'07:00', closeTime:'15:00', isReal:true,
    phone:'0577-8855-8899',
    tags:['Yum Cha','Dim Sum','Har Gow','Cart Service'],
    coverGradient:'linear-gradient(140deg,#1a0a00,#301500,#1a0a00)',
    coverEmoji:'🫖', accentColor:'#e8a030',
    description:'A century of Cantonese yum cha tradition — open every morning at 7am. Senior chefs handcraft har gow, siu mai and rice noodle rolls. Trolley service at peak hours.',
    features:['🫖 Authentic Yum Cha','🛒 Cart Service','👨‍🍳 Master Craftsmen','⏰ Breakfast & Lunch Only'],
    menuCategories:['Steamed','Fried','Congee','Tea'],
    menu:[
      {id:1,name:'Har Gow (Prawn Dumplings)',nameZh:'晶莹鲜虾饺',price:32,emoji:'🥟',category:'Steamed',desc:'The king of dim sum — translucent skin, crunchy prawn filling. The benchmark of any yum cha.',rating:4.9,orders:9876,isPopular:true},
      {id:2,name:'Siu Mai (Pork & Shrimp)',nameZh:'鲜虾猪肉烧卖',price:28,emoji:'🫕',category:'Steamed',desc:'Pork and prawn siu mai, topped with a coral dot of crab roe. Juicy and irresistible.',rating:4.8,orders:8765,isPopular:true},
      {id:3,name:'Shrimp Rice Noodle Roll',nameZh:'鲜虾肠粉',price:28,emoji:'🫔',category:'Steamed',desc:'Silky steamed rice sheet wrapped around fresh prawns, with sweet soy sauce.',rating:4.7,orders:6543,isPopular:true},
      {id:4,name:'Egg Tart',nameZh:'蛋挞',price:14,emoji:'🍮',category:'Fried',desc:'Flaky pastry shell with wobbly egg custard inside. Eat fresh from the oven.',rating:4.8,orders:11234,isPopular:false},
      {id:5,name:'Preserved Egg & Pork Congee',nameZh:'皮蛋瘦肉粥',price:22,emoji:'🍚',category:'Congee',desc:'Silky Cantonese congee with century egg and sliced pork. Comforting and warming.',rating:4.6,orders:4321,isPopular:false},
    ],
  },

  /* ── NEW RESTAURANTS ──────────────────────────────── */
  {
    id:'kfc', name:'KFC', nameZh:'肯德基',
    tagline:"World's Favourite Fried Chicken",
    cuisine:'Fast Food · American',
    categories:['fastfood','western'],
    priceLevel:1, avgPrice:38, rating:4.2, reviewCount:8765,
    address:'Wanxiang City Mall G/F, Minsheng Road, Ouhai District, Wenzhou',
    district:'Ouhai District', distance:'0.5km',
    hours:'07:00 – 23:00', openTime:'07:00', closeTime:'23:00', isReal:true,
    phone:'400-823-8080',
    tags:['Fried Chicken','Burger','Breakfast','Family'],
    coverGradient:'linear-gradient(140deg,#1a0500,#550000,#1a0500)',
    coverEmoji:'🍗', accentColor:'#e8220a',
    description:"Colonel Sanders' Original Recipe — 11 herbs and spices perfected since 1952. Crispy outside, juicy inside, every single time.",
    features:['🍗 Original Recipe','🥚 All-Day Breakfast','📱 KFC App Deals','🛵 Delivery'],
    menuCategories:['Chicken','Burger','Sides','Drink'],
    menu:[
      {id:1,name:'Original Recipe Chicken (2pc)',nameZh:'原味鸡 (2块)',price:29,emoji:'🍗',category:'Chicken',desc:'The Colonel\'s secret blend of 11 herbs and spices. Crispy golden crust, succulent inside.',rating:4.7,orders:45678,isPopular:true},
      {id:2,name:'Zinger Burger',nameZh:'劲辣鸡腿堡',price:24,emoji:'🍔',category:'Burger',desc:'Spicy crispy chicken fillet with lettuce, mayo and a hit of chilli in a toasted sesame bun.',rating:4.5,orders:32456,isPopular:true},
      {id:3,name:'Chicken Nuggets (10pc)',nameZh:'鸡块 (10块)',price:26,emoji:'🍗',category:'Chicken',desc:'Tender white breast meat nuggets, golden fried. Great with BBQ or sweet & sour dip.',rating:4.4,orders:28765,isPopular:true},
      {id:4,name:'Large Fries',nameZh:'大号薯条',price:16,emoji:'🍟',category:'Sides',desc:'Long-cut golden fries, lightly salted. The perfect KFC companion.',rating:4.3,orders:38901,isPopular:false},
      {id:5,name:'Corn on the Cob',nameZh:'玉米棒',price:9,emoji:'🌽',category:'Sides',desc:'Sweet steamed corn on the cob — a KFC classic side.',rating:4.4,orders:18765,isPopular:false},
      {id:6,name:'Original Egg Tart',nameZh:'葡式蛋挞',price:5,emoji:'🥚',category:'Sides',desc:'Flaky pastry shell with smooth vanilla egg custard. A KFC China signature.',rating:4.6,orders:55432,isPopular:false},
      {id:7,name:'Hot Wings (4pc)',nameZh:'辣翅 (4块)',price:22,emoji:'🔥',category:'Chicken',desc:'Crispy spiced chicken wings with a satisfying crunch and lingering heat.',rating:4.5,orders:23456,isPopular:false},
      {id:8,name:'Pepsi / 7UP',nameZh:'百事/七喜',price:9,emoji:'🥤',category:'Drink',desc:'Ice-cold fountain drink — the perfect match for crispy fried chicken.',rating:4.2,orders:65432,isPopular:false},
    ],
  },
  {
    id:'mcdonalds', name:"McDonald's", nameZh:'麦当劳',
    tagline:"I'm Lovin' It",
    cuisine:'Fast Food · American',
    categories:['fastfood','western'],
    priceLevel:1, avgPrice:42, rating:4.1, reviewCount:11234,
    address:'Wuma Street, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'0.9km',
    hours:'06:00 – 24:00', openTime:'06:00', closeTime:'24:00', isReal:true,
    phone:'400-920-0000',
    tags:['Big Mac','McNuggets','McFlurry','24-hour'],
    coverGradient:'linear-gradient(140deg,#1a1000,#3a2800,#1a1000)',
    coverEmoji:'🍔', accentColor:'#ffbc0d',
    description:"Open almost 24 hours. From the iconic Big Mac to McCafé coffees and McFlurry sundaes — the menu everyone knows and loves.",
    features:['⏰ Almost 24 Hours','☕ McCafé','🍦 McFlurry','📱 App Exclusive Deals'],
    menuCategories:['Burger','Chicken','Side','Dessert'],
    menu:[
      {id:1,name:'Big Mac',nameZh:'巨无霸',price:25,emoji:'🍔',category:'Burger',desc:'Two beef patties, special sauce, lettuce, cheese, pickles and onions on a sesame bun. Iconic.',rating:4.5,orders:56789,isPopular:true},
      {id:2,name:'McSpicy Deluxe',nameZh:'麦辣鸡腿堡',price:23,emoji:'🌶️',category:'Chicken',desc:'Spicy crispy chicken fillet on a brioche bun with fresh lettuce and creamy mayo.',rating:4.4,orders:43210,isPopular:true},
      {id:3,name:'McNuggets (6pc)',nameZh:'麦乐鸡 (6块)',price:19,emoji:'🍗',category:'Chicken',desc:'Tender all-white-meat chicken nuggets, perfectly shaped for dipping. A true classic.',rating:4.5,orders:67890,isPopular:true},
      {id:4,name:'Medium Fries',nameZh:'中号薯条',price:13,emoji:'🍟',category:'Side',desc:"World-famous thin-cut, lightly salted fries. Always fresh, always perfect.",rating:4.4,orders:78901,isPopular:false},
      {id:5,name:'McFlurry Oreo',nameZh:'奥利奥麦旋风',price:15,emoji:'🍦',category:'Dessert',desc:'Creamy vanilla soft serve swirled with crushed Oreo cookies. Impossibly refreshing.',rating:4.6,orders:34567,isPopular:false},
      {id:6,name:'Hash Brown',nameZh:'薯饼',price:7,emoji:'🟨',category:'Side',desc:'Crispy golden potato cake — breakfast essential, great any time of day.',rating:4.3,orders:28765,isPopular:false},
      {id:7,name:'Apple Pie',nameZh:'苹果派',price:8,emoji:'🥧',category:'Dessert',desc:'Baked pastry with hot cinnamon apple filling. Let it cool slightly — seriously.',rating:4.4,orders:23456,isPopular:false},
      {id:8,name:'McCafé Americano',nameZh:'麦咖啡美式',price:14,emoji:'☕',category:'Dessert',desc:'100% arabica espresso with water. Clean, bold and far better than you might expect.',rating:4.2,orders:19876,isPopular:false},
    ],
  },
  {
    id:'burger-king', name:'Burger King', nameZh:'汉堡王',
    tagline:'Have It Your Way',
    cuisine:'Fast Food · American',
    categories:['fastfood','western'],
    priceLevel:1, avgPrice:36, rating:4.0, reviewCount:5432,
    address:'Times Square B1, Longwan District, Wenzhou',
    district:'Longwan District', distance:'4.0km',
    hours:'08:00 – 22:30', openTime:'08:00', closeTime:'22:30', isReal:true,
    phone:'400-088-8888',
    tags:['Whopper','Flame-grilled','Onion Rings','BK'],
    coverGradient:'linear-gradient(140deg,#1a0800,#3a1500,#1a0800)',
    coverEmoji:'👑', accentColor:'#e87808',
    description:'Flame-grilled since 1954. The Whopper — made to order, your way. Real fire, real flavour.',
    features:['🔥 Flame-grilled','🍔 Custom Orders','🧅 Famous Onion Rings','🛵 Delivery'],
    menuCategories:['Burger','Sides','Drink'],
    menu:[
      {id:1,name:'Whopper',nameZh:'皇堡',price:28,emoji:'🍔',category:'Burger',desc:'Quarter-pound flame-grilled beef with tomatoes, lettuce, onion, pickles, ketchup and mayo.',rating:4.4,orders:34567,isPopular:true},
      {id:2,name:'Double Whopper',nameZh:'双层皇堡',price:38,emoji:'🍔',category:'Burger',desc:'Two flame-grilled patties, same great build. For the seriously hungry.',rating:4.3,orders:18765,isPopular:true},
      {id:3,name:'Crispy Chicken Royale',nameZh:'皇家鸡腿堡',price:22,emoji:'🍗',category:'Burger',desc:'Crispy chicken fillet with lettuce and mayo on a sesame seed bun.',rating:4.2,orders:23456,isPopular:false},
      {id:4,name:'Onion Rings (M)',nameZh:'洋葱圈 (中)',price:14,emoji:'🧅',category:'Sides',desc:'Thick-cut onion rings in crispy golden batter. BK\'s most famous side.',rating:4.5,orders:28765,isPopular:false},
      {id:5,name:'Mozzarella Sticks (4pc)',nameZh:'芝士条',price:16,emoji:'🧀',category:'Sides',desc:'Gooey mozzarella in crispy breading, with marinara dipping sauce.',rating:4.3,orders:14567,isPopular:false},
      {id:6,name:'BK Shake (Chocolate)',nameZh:'巧克力奶昔',price:17,emoji:'🥤',category:'Drink',desc:'Thick and creamy chocolate milkshake. The indulgent way to wash down a Whopper.',rating:4.4,orders:12345,isPopular:false},
    ],
  },
  {
    id:'pizza-hut', name:'Pizza Hut', nameZh:'必胜客',
    tagline:'No One Outpizzas the Hut',
    cuisine:'Fast Food · Italian',
    categories:['fastfood','western'],
    priceLevel:2, avgPrice:68, rating:4.1, reviewCount:6789,
    address:'Henglong Plaza 2F, Renmin Road, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'1.9km',
    hours:'10:00 – 22:00', openTime:'10:00', closeTime:'22:00', isReal:true,
    phone:'400-888-0099',
    tags:['Pizza','Pasta','Delivery','Family'],
    coverGradient:'linear-gradient(140deg,#1a0000,#450000,#1a0000)',
    coverEmoji:'🍕', accentColor:'#cc0000',
    description:"Dine-in or delivery — Pizza Hut's pan pizza with thick, buttery crust is a comfort food classic. Pasta, wings and salad round out the menu.",
    features:['🍕 Dine-in & Delivery','🍝 Pasta & Risotto','🍗 Chicken Wings','🥗 Salad Bar'],
    menuCategories:['Pizza','Pasta','Sides','Drink'],
    menu:[
      {id:1,name:'Margherita (9-inch)',nameZh:'玛格丽特披萨 9寸',price:59,emoji:'🍕',category:'Pizza',desc:'San Marzano tomato, mozzarella, fresh basil on a crispy-edged pan crust. The original.',rating:4.2,orders:23456,isPopular:true},
      {id:2,name:'Pepperoni (9-inch)',nameZh:'意式香肠披萨 9寸',price:69,emoji:'🍕',category:'Pizza',desc:'Loaded with pepperoni slices and mozzarella. The crowd-pleaser.',rating:4.3,orders:34567,isPopular:true},
      {id:3,name:'BBQ Chicken (9-inch)',nameZh:'BBQ鸡肉披萨 9寸',price:69,emoji:'🍕',category:'Pizza',desc:'Smoky BBQ base, grilled chicken, red onion and sweetcorn. Sweet and hearty.',rating:4.2,orders:21098,isPopular:false},
      {id:4,name:'Baked Pasta',nameZh:'焗意面',price:48,emoji:'🍝',category:'Pasta',desc:'Al dente pasta baked in a rich tomato sauce, topped with bubbling mozzarella.',rating:4.1,orders:16543,isPopular:false},
      {id:5,name:'Chicken Wings (6pc)',nameZh:'烤鸡翅 (6块)',price:38,emoji:'🍗',category:'Sides',desc:'Roasted chicken wings with your choice of original, BBQ or spicy glaze.',rating:4.3,orders:28765,isPopular:false},
      {id:6,name:'Garlic Bread',nameZh:'蒜香面包',price:18,emoji:'🥖',category:'Sides',desc:'Thick-cut bread toasted with garlic butter. Great for mopping up the sauce.',rating:4.2,orders:19876,isPopular:false},
    ],
  },
  {
    id:'haidilao', name:'Haidilao Hot Pot', nameZh:'海底捞',
    tagline:'Premium Hot Pot & Legendary Service',
    cuisine:'Hot Pot · Chinese',
    categories:['hotpot','chinese'],
    priceLevel:3, avgPrice:168, rating:4.8, reviewCount:12345,
    address:'Wanxiang City Mall 4F, Minsheng Road, Ouhai District, Wenzhou',
    district:'Ouhai District', distance:'1.1km',
    hours:'10:00 – 02:00', openTime:'10:00', closeTime:'02:00', isReal:true,
    phone:'0577-8800-1234',
    tags:['Hot Pot','Premium','Service Excellence','Noodle Performance'],
    coverGradient:'linear-gradient(140deg,#1a0000,#3d0808,#1a0000)',
    coverEmoji:'🫕', accentColor:'#e84040',
    description:"China's most celebrated hot pot chain — legendary service, premium ingredients and theatrical hand-pulled noodle performances. The wait is always worth it.",
    features:['💇 Free Manicure While Waiting','🎭 Noodle Dance Performance','🧸 Stuffed Animal Dining Partners','🍦 Free Ice Cream'],
    menuCategories:['Broth','Meat','Seafood','Veg','Performance'],
    menu:[
      {id:1,name:'Classic Mala Broth',nameZh:'经典麻辣锅底',price:68,emoji:'🌶️',category:'Broth',desc:'The signature deep red Sichuan tallow broth — numbing, intensely flavoured and utterly addictive.',rating:4.9,orders:23456,isPopular:true},
      {id:2,name:'Tomato Broth',nameZh:'番茄锅底',price:48,emoji:'🍅',category:'Broth',desc:'Fresh tomato base, naturally sweet and tangy. Perfect for non-spicy lovers or as the mild half of a yin-yang pot.',rating:4.7,orders:18765,isPopular:true},
      {id:3,name:'Fresh Wagyu Beef Slices',nameZh:'新鲜肥牛',price:108,emoji:'🥩',category:'Meat',desc:'Premium wagyu-style beef, sliced daily. Melts the moment it hits the broth.',rating:4.9,orders:19876,isPopular:true},
      {id:4,name:'Handmade Beef Balls',nameZh:'手打牛肉丸',price:38,emoji:'⚪',category:'Meat',desc:'Made fresh in-house daily — bouncy, beefy, irresistibly chewy.',rating:4.8,orders:16543,isPopular:false},
      {id:5,name:'Hand-pulled Noodle Performance',nameZh:'变形表演·现拉面',price:18,emoji:'🎭',category:'Performance',desc:'Our chef performs a theatrical noodle-pulling dance before adding your noodles live to the pot.',rating:5.0,orders:21098,isPopular:true},
      {id:6,name:'Prawn Paste',nameZh:'鲜虾滑',price:48,emoji:'🦐',category:'Seafood',desc:'Fresh prawn paste — mold on a chopstick and drop into the broth to form silky prawn balls.',rating:4.7,orders:12345,isPopular:false},
      {id:7,name:'Brain-numbing Tofu',nameZh:'脑花豆腐',price:22,emoji:'🫘',category:'Veg',desc:'Silky soft tofu that soaks up every flavour of the broth. Surprisingly the dish everyone loves.',rating:4.6,orders:14567,isPopular:false},
      {id:8,name:'Free Ice Cream',nameZh:'免费冰淇淋',price:0,emoji:'🍦',category:'Veg',desc:'Complimentary soft-serve ice cream at the end of every meal. A Haidilao tradition.',rating:4.9,orders:23456,isPopular:false},
    ],
  },
  {
    id:'starbucks', name:'Starbucks', nameZh:'星巴克',
    tagline:'Coffee & Community',
    cuisine:'Café · Coffee',
    categories:['cafe'],
    priceLevel:2, avgPrice:38, rating:4.3, reviewCount:9876,
    address:'1 Wuma Street, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'0.6km',
    hours:'07:00 – 22:00', openTime:'07:00', closeTime:'22:00', isReal:true,
    phone:'400-007-2220',
    tags:['Coffee','Matcha','Frappuccino','Work-friendly'],
    coverGradient:'linear-gradient(140deg,#001a10,#003520,#001a10)',
    coverEmoji:'☕', accentColor:'#00a862',
    description:'Your third place between home and work. Expertly roasted arabica, seasonal specials, and a welcoming space to sit and stay.',
    features:['📶 Free WiFi','☕ Reserve Bar','🥛 Oat/Soy Options','📱 Starbucks App Rewards'],
    menuCategories:['Espresso','Matcha','Cold','Food'],
    menu:[
      {id:1,name:'Caramel Macchiato',nameZh:'焦糖玛奇朵',price:38,emoji:'☕',category:'Espresso',desc:'Steamed milk with vanilla syrup, espresso and a caramel drizzle. The Starbucks classic.',rating:4.5,orders:23456,isPopular:true},
      {id:2,name:'Matcha Latte',nameZh:'抹茶拿铁',price:36,emoji:'🍵',category:'Matcha',desc:'High-quality ceremonial matcha whisked into steamed milk. Rich and earthy.',rating:4.6,orders:28765,isPopular:true},
      {id:3,name:'Cold Brew',nameZh:'冷萃咖啡',price:38,emoji:'🧊',category:'Cold',desc:'Slow-steeped for 20 hours — naturally sweet, smooth and never bitter. Highly caffeinated.',rating:4.7,orders:19876,isPopular:true},
      {id:4,name:'Pike Place Roast (M)',nameZh:'派克市场烘焙',price:28,emoji:'☕',category:'Espresso',desc:'A smooth, balanced medium roast. The Starbucks everyday coffee — reliable and comforting.',rating:4.2,orders:34567,isPopular:false},
      {id:5,name:'Croissant',nameZh:'牛角包',price:22,emoji:'🥐',category:'Food',desc:'Flaky, buttery all-butter croissant. Perfect with any coffee.',rating:4.3,orders:18765,isPopular:false},
      {id:6,name:'Blueberry Muffin',nameZh:'蓝莓松饼',price:28,emoji:'🫐',category:'Food',desc:'Moist muffin loaded with fresh blueberries and a crumbly sugar top.',rating:4.2,orders:12345,isPopular:false},
    ],
  },
  {
    id:'tim-hortons', name:"Tim Hortons", nameZh:'蒂姆霍顿斯',
    tagline:"Always Fresh",
    cuisine:'Café · Canadian',
    categories:['cafe'],
    priceLevel:1, avgPrice:28, rating:4.2, reviewCount:4321,
    address:'Xintiandi, Wuma Street, Lucheng District, Wenzhou',
    district:'Lucheng District', distance:'0.7km',
    hours:'06:30 – 21:30', openTime:'06:30', closeTime:'21:30', isReal:true,
    phone:'400-820-0999',
    tags:['Coffee','Timbits','Breakfast','Canadian'],
    coverGradient:'linear-gradient(140deg,#0a0a00,#1a1500,#0a0a00)',
    coverEmoji:'🍩', accentColor:'#cc0000',
    description:"Canada's beloved coffee chain — always fresh, never from a pot that's been sitting too long. Timbits, bagels and the iconic Double Double.",
    features:['☕ Always Fresh Coffee','🍩 Timbits','🥯 Bagels','🍁 Canadian Spirit'],
    menuCategories:['Coffee','Food','Drink'],
    menu:[
      {id:1,name:'Double Double',nameZh:'二加二咖啡',price:22,emoji:'☕',category:'Coffee',desc:'Two creams, two sugars — the quintessential Canadian order. Smooth and comforting.',rating:4.4,orders:18765,isPopular:true},
      {id:2,name:'Iced Capp',nameZh:'冰卡布奇诺',price:24,emoji:'🧊',category:'Coffee',desc:'Frozen coffee and cream blended smooth. The Tim Hortons summer signature.',rating:4.5,orders:14567,isPopular:true},
      {id:3,name:'Timbits (10pc)',nameZh:'提姆比特 10个',price:16,emoji:'🍩',category:'Food',desc:'Bite-sized donut holes in original glazed, chocolate and blueberry. Dangerously moreish.',rating:4.6,orders:23456,isPopular:true},
      {id:4,name:'Bacon & Egg Muffin',nameZh:'培根蛋松饼',price:25,emoji:'🥚',category:'Food',desc:'Toasted English muffin with a fresh-cracked egg and crispy bacon.',rating:4.3,orders:12345,isPopular:false},
      {id:5,name:'Everything Bagel + Cream Cheese',nameZh:'百味百吉饼',price:22,emoji:'🥯',category:'Food',desc:'Sesame, poppy seed and onion-topped bagel toasted and spread generously with cream cheese.',rating:4.4,orders:9876,isPopular:false},
      {id:6,name:'Chocolate Chip Cookie',nameZh:'巧克力曲奇',price:10,emoji:'🍪',category:'Food',desc:'Thick, chewy and warm. The freshest batch always sells out by noon.',rating:4.5,orders:18765,isPopular:false},
    ],
  },
  {
    id:'nanjing-impressions', name:'Nanjing Impressions', nameZh:'南京大牌档',
    tagline:'Classic Jiangnan Comfort Food',
    cuisine:'Jiangnan · Chinese',
    categories:['chinese'],
    priceLevel:2, avgPrice:98, rating:4.7, reviewCount:5678,
    address:'Century Lotus Commercial Centre 3F, Chezhan Avenue, Ouhai District, Wenzhou',
    district:'Ouhai District', distance:'2.2km',
    hours:'10:30 – 22:00', openTime:'10:30', closeTime:'22:00', isReal:true,
    phone:'0577-8866-7788',
    tags:['Jiangnan','Duck','Soup Dumpling','Nostalgic'],
    coverGradient:'linear-gradient(140deg,#0a0a00,#1c1500,#0a0a00)',
    coverEmoji:'🏮', accentColor:'#c8a850',
    description:"Jiangnan comfort food in a vibrant old-style Nanjing teahouse setting. Salted duck, rich bone broth and hand-folded dumplings — nostalgic and deeply satisfying.",
    features:['🦆 Signature Salted Duck','🍲 Slow-cooked Broth','🥟 Handmade Dumplings','🏮 Old Nanjing Décor'],
    menuCategories:['Cold Dish','Hot Dish','Noodle','Dim Sum'],
    menu:[
      {id:1,name:'Nanjing Salted Duck',nameZh:'南京盐水鸭',price:68,emoji:'🦆',category:'Cold Dish',desc:'Brined with Chinese spices, slow-cooked and chilled. Silky, fragrant and the city\'s most famous dish.',rating:4.9,orders:8765,isPopular:true},
      {id:2,name:'Broth Soup Dumplings',nameZh:'汤汁灌汤包',price:36,emoji:'🥟',category:'Dim Sum',desc:'Large steamed dumplings filled with rich bone broth. Sip through a straw — careful, they\'re hot.',rating:4.8,orders:6543,isPopular:true},
      {id:3,name:'Dry-Tossed Noodles',nameZh:'干拌面',price:28,emoji:'🍜',category:'Noodle',desc:'Freshly pulled noodles tossed in a rich soy-sesame sauce with minced pork and pickled mustard.',rating:4.7,orders:5432,isPopular:true},
      {id:4,name:'Lion\'s Head Meatball',nameZh:'狮子头',price:58,emoji:'🧆',category:'Hot Dish',desc:'Giant braised pork meatball with napa cabbage. Soft, fatty and deeply savoury.',rating:4.8,orders:4321,isPopular:false},
      {id:5,name:'Pork Belly with Plum Sauce',nameZh:'梅菜扣肉',price:52,emoji:'🥩',category:'Hot Dish',desc:'Meltingly tender pork belly layered over preserved mustard greens. Steamed and sticky-sweet.',rating:4.7,orders:3456,isPopular:false},
    ],
  },
];

/* ── Helper functions ────────────────────────────────── */

function getRestaurantById(id) {
  return RESTAURANTS.find(r => r.id === id) || null;
}

function searchRestaurants(query) {
  if (!query || !query.trim()) return RESTAURANTS;
  const q = query.trim().toLowerCase();
  return RESTAURANTS.filter(r =>
    r.name.toLowerCase().includes(q) ||
    r.nameZh.includes(q) ||
    r.cuisine.toLowerCase().includes(q) ||
    r.district.toLowerCase().includes(q) ||
    r.tags.some(t => t.toLowerCase().includes(q)) ||
    r.menu.some(m => m.name.toLowerCase().includes(q) || m.nameZh.includes(q) || m.category.toLowerCase().includes(q))
  );
}

function filterByCategory(category) {
  if (!category || category === 'all') return RESTAURANTS;
  return RESTAURANTS.filter(r => r.categories && r.categories.includes(category));
}

function getRecommended(n = 8) {
  return [...RESTAURANTS].sort((a, b) => b.rating * Math.log(b.reviewCount + 1) - a.rating * Math.log(a.reviewCount + 1)).slice(0, n);
}

function priceSymbol(level) {
  return '¥'.repeat(level) + '<span style="opacity:.3">¥</span>'.repeat(4 - level);
}

function starsHtml(rating) {
  const full  = Math.floor(rating);
  const empty = 5 - full;
  return '<span style="color:#f5c518">' + '★'.repeat(full) + '</span>' +
         '<span style="color:rgba(255,255,255,.2)">' + '★'.repeat(empty) + '</span>';
}

function simulatedAvailability(restaurantId) {
  const seed = restaurantId.split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  const rand  = (min, max) => min + ((seed * 9301 + 49297) % 233280 % (max - min + 1));
  return {
    small:   { total: rand(8, 20), available: rand(0, 8) },
    medium:  { total: rand(5, 15), available: rand(0, 6) },
    large:   { total: rand(3, 10), available: rand(0, 4) },
    private: { total: rand(2, 6),  available: rand(0, 3) },
  };
}

function availabilityBadge(avail) {
  let totalAvail = 0, totalCount = 0;
  Object.values(avail).forEach(v => { totalAvail += v.available; totalCount += v.total; });
  const pct = totalCount > 0 ? totalAvail / totalCount : 0;
  if (pct === 0) return '<span class="avail-chip full">● Fully Booked</span>';
  if (pct < 0.2)  return '<span class="avail-chip tight">● Almost Full</span>';
  if (pct < 0.5)  return '<span class="avail-chip ok">● Limited Seats</span>';
  return             '<span class="avail-chip good">● Available</span>';
}
